osx_image: xcode9 
language: objective-c
xcode_sdk: iphonesimulator 
cache: cocoapods 
xcode_xcworkspace: IQUITestCodeMaker.xcworkspace
xcode_scheme: IQUITestCodeMaker
podfile: IQUITestCodeMaker/Podfile 
env: 
global: 
- LANG=en_US.UTF-8 
- LC_ALL=en_US.UTF-8 
- XCODE_WORKSPACE=IQUITestCodeMaker/IQUITestCodeMaker.xcworkspace 
matrix: 
- SCHEME="IQUITestCodeMaker" 
before_install: 
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet  
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet 
- pod install --repo-update 
script: 
- set -o pipefail 
- xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build | xcpretty
after_success: 
- sleep 5 
