osx_image: xcode9 
language: objective-c
notifications:
  email: zhiwei.geek@gmail.com
env: 
global: 
- LANG=en_US.UTF-8 
- LC_ALL=en_US.UTF-8 
matrix: 
- SCHEME="IQUITestCodeMaker" 
before_install: 
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet  
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet 
- pod install --repo-update 
script: 
- set -o pipefail 
- echo Build as static library
- xcodebuild clean build -workspace IQUITestCodeMaker.xcworkspace -scheme 'IQUITestCodeMaker' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
after_success: 
- sleep 5 
